### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by DanieleSuppo** [BSData/zone-raiders#2]
As per documentation I'm asking to be a collaborator of this repository.
We already started writing some datafile with a friend and I already opened a pull request

Thanks
Daniele

**Comment by amis92** [comment]
@efalsken ?

**Comment by DanieleSuppo** [comment]
Sorry guys, any news on this?

**Comment by amis92** [comment]
Well since there was no response from the only maintainer, I'll just go ahead and invite you.

---

Hello, @DanieleSuppo. Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Also, join the data author community over at discord!

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Cheers!

[invitation]: https://github.com/BSData/zone-raiders/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
